version: '3.7'

services:
  my_backend:
    image: asia.gcr.io/disco-catcher-359906/my-backend:2.1
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
    # env_file:
    #   - ./.env.prod
    volumes:
      - ./src:/my_backend/src
    ports:
      - 3000:3000

  # my_database:
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'myprod04'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   # command:
  #   #   - --character-set-server=utf8mb4
  #   #   - --collation-server=utf8mb4_unicode_ci
  #   #   - --skip-character-set-client-handshake
  #   # cap_add:
  #   #   - SYS_NICE
  #   ports:
  #     - 3306:3306
