version: '3.7'

services:
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/my_backend/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev

  my_database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'mydev04'
      MYSQL_ROOT_PASSWORD: 'root'
    # command:
    #   - --character-set-server=utf8mb4
    #   - --collation-server=utf8mb4_unicode_ci
    #   - --skip-character-set-client-handshake
    # cap_add:
    #   - SYS_NICE
    ports:
      - 3306:3306